# Parametri di performance di Gradle (puoi mantenerli così)
org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false

# Versioni di progetto
appName=AstroInvasion
projectVersion=Beta
gdxVersion=1.13.0
graalHelperVersion=2.0.1
enableGraalNative=false
